### ISSUE TITLE
[Bazel CI] Error in Cargo bazel bootstrap with Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_jsonnet#194]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/4026#01910c21-49f3-45fd-acae-1bbcff496945

 Platform: MacOS

 Logs: 
```
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/external/rules_rust+/crate_universe/extension.bzl", line 348, column 37, in _crate_impl
		_generate_hub_and_spokes(module_ctx, cargo_bazel, cfg, annotations, packages = packages)
	File "/private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/external/rules_rust+/crate_universe/extension.bzl", line 139, column 16, in _generate_hub_and_spokes
		cargo_bazel([
	File "/private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/external/rules_rust+/crate_universe/private/module_extensions/cargo_bazel_bootstrap.bzl", line 55, column 17, in run
		fail("%s returned with exit code %d:\n%s" % (pretty_args, result.return_code, result.stderr))
Error in fail: /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/cargo-bazel generate --cargo-lockfile /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/crates/splicing-output/Cargo.lock --config /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/crates/config.json --splicing-manifest /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/crates/splicing_manifest.json --repository-dir /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/crates --metadata /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/crates/splicing-output/metadata.json --repin --lockfile /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/modextwd/rules_rust++crate/crates/lockfile.json --cargo /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/external/rules_rust++rust_host_tools+rust_host_tools/bin/cargo --rustc /private/var/tmp/_bazel_buildkite/ba06ce64824d64f3e8c04308c82ef3d8/external/rules_rust++rust_host_tools+rust_host_tools/bin/rustc returned with exit code 101:
thread 'main' panicked at src/utils.rs:48:22:
Could not rename paths: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Target //jsonnet:stamper up-to-date:
  bazel-bin/jsonnet/stamper
(06:12:14) ERROR: Analysis of target '//jsonnet:rust_jsonnet' failed; build aborted: error evaluating module extension crate in @@rules_rust+//crate_universe:extension.bzl
(06:12:14) INFO: Elapsed time: 69.710s, Critical Path: 0.07s
(06:12:14) INFO: 5 processes: 5 internal.
(06:12:14) ERROR: Build did NOT complete successfully
(06:12:14) FAILED:
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/rules_jsonnet
git reset 04221a66b57bba1f9ad387e59103c34fb8ea531a  --hard
export USE_BAZEL_VERSION=a7264d99e2d14463cb683a4091d5ad0e08431205
bazel build //... 
 ``` 
 CC Greenteam @fweikert

**Comment by sgowroji** [comment]
CC @EdSchouten

**Comment by deepalak56** [comment]
Since the rules_jsonnet has been disabled from Bazel CI, we are closing this issue.

[Disable rules_jsonnet in downstream pipeline](https://github.com/fweikert/continuous-integration/commit/386b8b8d77809296bad4346a4f3b3180218edd4c)
