### ISSUE TITLE
Fix Bazel --all_incompatible_changes

### ISSUE THREAD

**Issue by qzmfranklin** [bazelbuild/rules_jsonnet#97]
Some of the .bzl files use legacy starlark constructs that have been deprecated.  The flag `--all_incompatible_changes` surfaces a few instances as such.

For example:
```
INFO: Invocation ID: d32772b6-fc44-4f2e-9ff4-26780574b35d
ERROR: /home/zhongming/git/LogiOcean/examples/jsonnet/BUILD:186:1: in jsonnet_to_json_test rule //examples/jsonnet:yaml_stream_test: 
Traceback (most recent call last):
        File "/home/zhongming/git/LogiOcean/examples/jsonnet/BUILD", line 186
                jsonnet_to_json_test(name = 'yaml_stream_test')
        File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/io_bazel_rules_jsonnet/jsonnet/jsonnet.bzl", line 355, in _jsonnet_to_json_test_impl
                ctx.file_action(output = ctx.outputs.executable, c...), ...)
Use ctx.actions.write instead of ctx.file_action. 
Use --incompatible_new_actions_api=false to temporarily disable this check.
```

Would like these incompatible changes to get cleaned up.

**Comment by Globegitter** [comment]
This should be fixed.
